# Simulate a job ending in error
import time

print ("ERROR")

os.exit (1)
